# Generated by Django 4.2.23 on 2025-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhistory',
            name='from_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='to_currency',
            field=models.CharField(max_length=3),
        ),
    ]
